### ISSUE TITLE
Internationalization and Language Support - Decouple Strings

### ISSUE THREAD

**Issue by alayek** [DevBlend/zenias-python#6]
I noticed a lot of strings have been hard-coded in the scripts. We might want to move them out and put in a separate directory under en-GB or en-US or something.

This also gives us a way of expanding our tool to non-English users.

**Comment by mtancoigne** [comment]
Can you make a prototype ?

**Comment by ghost** [comment]
@alayek This is a very good idea. I've made a milestone and specific label for this. Please create specific issues and assign them to the milestone, for each task.

**Comment by mtancoigne** [comment]
I changed this to the next-next version, so this will be done.
