### ISSUE TITLE
Switch all the boxes to ubuntu 32 bits

### ISSUE THREAD

**Issue by mtancoigne** [DevBlend/zenias-python#7]
It's really important. Users may not have a 64bits architecture on their computers. And 32bits works both on 32 and 64.

**So** please, change your boxes now.**

**Comment by mtancoigne** [comment]
I'll do the PHP ones and the skeletton.

**Comment by mtancoigne** [comment]
BTW, hashicorps don't provide 32b boxes, so we should move to https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-i386-vagrant-disk1.box

**Comment by ghost** [comment]
@mtancoigne, I will implement this for the `bootstrap` and `node` boxes!

**Comment by alayek** [comment]
I think we can do one better. Get the underlying architecture, and assign accordingly. If it's `x86_64`, go for 64 bit `minimal/trusty64`. Otherwise, use `reelio/trusty32` or something similar.

Is that possible with Vagrantfile?

**Comment by alayek** [comment]
No idea why it shows

> mtancoigne was unassigned by alayek 3 minutes ago

I didn't do anything :confused:

**Comment by ghost** [comment]
@alayek, probably cause he left the github teams...
